apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-tac-toe-server
  template:
    metadata:
      labels:
        app: tic-tac-toe-server
    spec:
      containers:
      - name: server
        image: vladisto100/tic-tac-toe-server:latest
        ports:
        - containerPort: 9999

---
apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-server
spec:
  selector:
    app: tic-tac-toe-server
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
