name: Docker Image CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  server-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
     
      - name: Extract tag name
        id: tag_name
        run: echo "::set-output name=TAG_NAME::$(echo ${GITHUB_REF#refs/tags/})"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, Scan, and Push Server Image
        uses: docker/build-push-action@v2
        with:
         context: .
         file: server/Dockerfile
         push: true
         tags: vladisto100/tic-tac-toe:server:${{ steps.tag_name.outputs.TAG_NAME }},vladisto100/tic-tac-toe:server:latest
      - name: Build, Scan, and Push Client Image
        uses: docker/build-push-action@v2
        with:
         context: .
         file: client/Dockerfile
         push: true
         tags: vladisto100/tic-tac-toe:client:${{ steps.tag_name.outputs.TAG_NAME }},vladisto100/tic-tac-toe:client:latest


