name: Markdown Formatting and Checking

on:
  push:
    paths:
      - '**/*.md'
  pull_request:
    paths:
      - '**/*.md'

jobs:
  format-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Prettier
        run: npm install --global prettier

      - name: Format Markdown files
        run: prettier --write "**/*.md"

      - name: Commit formatted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automatically format Markdown files'
          file_pattern: "*.md"
          branch: ${{ github.head_ref }}

  lint-markdown:
    runs-on: ubuntu-latest
    needs: [format-markdown]
    steps:
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Lint Markdown files
        run: markdownlint "**/*.md" || true
